$( document ).ready(function() {
$("#one").hide();
$("#two").hide();
$("#three").hide();
$("#four").hide();
$("#five").hide();
$("#six").hide();
$("#stage1").hide();
$("#stage2").hide();
$("#seven").hide();
$("#eight").hide();
$("#nine").hide();
$("#ten").hide();
$("#eleven").hide();
$("#twelve").hide();
$("#stage3").hide();
$("#thirteen").hide();
$("#fourteen").hide();
$("#fifteen").hide();
$("#sixteen").hide();
 $("#seventeen").hide();
$("#eighteen").hide();
$("#nineteen").hide();
$("#twenty").hide();
$("#twentyone").hide();
$("#twentytwo").hide();
$("#twentythree").hide();
$("#twentyfour").hide();
$("#twentyfive").hide();
$("#twentysix").hide();
$("#twentyseven").hide();
$("#twentyeight").hide();
$("#twentynine").hide();
$("#thirty").hide();
$("#bomb").hide();
$("#bomb2").hide();
$("#bomb3").hide();
$("#bomb4").hide();
$("#bomb5").hide();
$("#bomb6").hide();
$("#bomb7").hide();
$("#bomb8").hide();
$("#bomb9").hide();
$("#bomb10").hide();
$("#bomb11").hide();
$("#bomb12").hide();
$("#bomb13").hide();
$("#bomb14").hide();
$("#bomb15").hide();
$("#bomb16").hide();
$("#bomb17").hide();
$("#bomb18").hide();
$("#bomb19").hide();
$("#bomb20").hide();
$("#bomb21").hide();
$("#bomb22").hide();
$("#bomb23").hide();
$("#bomb24").hide();
$("#stagefour").hide();
$("#laststage").hide();
$("#end").hide();
$("#pagerefresh").hide();
$("#word").hide();
$("#wordtwo").hide();
$("#wordthree").hide();
$("#wordfour").hide();
$("#wordfive").hide();
$("#wordsix").hide();
$("#wordseven").hide();
$("#wordeight").hide();
$("#di").hide();
$("#picture").hide();
$("#skip").hide();
$("#gameover").hide();
$("#boxes").hide();
$("#begin").hide();
$("#back").hide();
$("#iword").hide();
$("#iword2").hide();
$("#word3").hide();
$("#word4").hide();
$("#word5").hide();
$("#word6").hide();
$("#word7").hide();
$("#word8").hide();
$("#word9").hide();
$("#word10").hide();
$("#word11").hide();
$("#box").hide();


$("#pagerefresh").click(function(){
$("#gameover").hide();
$("#pagerefresh").hide();
$("#title").delay(1000).fadeIn();
$("#title2").delay(2000).fadeIn();
$("#start").delay(3000).fadeIn();
$("#instruction").delay(4000).fadeIn();
});

$("#skip").click(function(){
$("#word").hide();
$("#picture").hide();
$("#di").hide();
$("#wordtwo").hide();
$("#wordthree").hide();
$("#wordfour").hide();
$("#wordfive").hide();
$("#wordsix").hide();
$("#wordseven").hide();
$("#start").delay(1000).fadeIn();
$("#instruction").delay(2000).fadeIn();
});
  
  $("#instruction").click(function(){    
    $("#title").hide();
    $("#title2").hide();
    $("#instruction").hide();
 $("#box").delay(1000).fadeIn();
  $("#iword").delay(2000).fadeIn();
$("#iword2").delay(3000).fadeIn();
  $("#word3").delay(4000).fadeIn();
  $("#word4").delay(5000).fadeIn();
  $("#word5").delay(6000).fadeIn();  
  $("#word6").delay(7000).fadeIn();
 $("#word7").delay(8000).fadeIn();
   $("#word8").delay(9000).fadeIn();
  $("#word9").delay(10000).fadeIn();
 $("#word10").delay(11000).fadeIn();
 $("#word11").delay(12000).fadeIn();
  $("#back").delay(13000).fadeIn();
    $("#start").hide();
 });


$("#start").click(function(){
  $("#start").hide();
  $("#one").show();
  $("#one").fadeOut(2500);
  $("#stage1").show();
  $("#stage1").fadeOut(2500);
  $("#instruction").hide();
  $("#title").hide();
  $("#title2").hide();
});
$("#one").click(function(){
  $("#three").show();
   $("#three").fadeOut(2500);
  $("#one").hide();
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover").delay(5000).fadeIn();
});
$("#three").click(function(){
  $("#pagerefresh").hide();
  $("#gameover").hide();
  $("#two").show();
    $("#two").fadeOut(2500);
    $("#three").hide();
    $("#pagerefresh").delay(5000).fadeIn();
    $("#gameover").delay(5000).fadeIn();
});
$("#two").click(function(){
   $("#pagerefresh").hide();
  $("#gameover").hide();
  $("#four").show();
  $("#four").fadeOut(2500);
  $("#two").hide();
$("#pagerefresh").delay(5000).fadeIn();
    $("#gameover").delay(5000).fadeIn();
});
$("#four").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
  $("#five").show();
    $("#five").fadeOut(2500);
  $("#four").hide();
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover").delay(5000).fadeIn();
});
$("#five").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
  $("#six").show();
   $("#six").fadeOut(2500);
  $("#five").hide();
});
$("#six").click(function(){
   $("#pagerefresh").hide();
  $("#gameover").hide();
  $("#stage2").show();
  $("#stage2").fadeOut(2500);
  $("#seven").show();
  $("#seven").fadeOut(2000);
  $("#six").hide();
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover").delay(5000).fadeIn();
});
$("#seven").click(function(){
   $("#pagerefresh").hide();
  $("#gameover").hide();
  $("#seven").hide();
  $("#eight").show();
  $("#eight").fadeOut(2000);
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover").delay(5000).fadeIn();
});
$("#eight").click(function(){
   $("#pagerefresh").hide();
     $("#gameover").hide();
  $("#eight").hide();
  $("#nine").show();
  $("#nine").fadeOut(2000);
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover").delay(5000).fadeIn();
});
$("#nine").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
  $("#nine").hide();
  $("#ten").show();
  $("#ten").fadeOut(2000);
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover").delay(5000).fadeIn();
});
$("#ten").click(function(){
   $("#pagerefresh").hide();
$("#gameover").hide();
$("#ten").hide();  
$("#eleven").show();
$("#eleven").fadeOut(2000);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
});
$("#eleven").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
  $("#eleven").hide();
  $("#twelve").show();
  $("#twelve").fadeOut(2000);
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover").delay(5000).fadeIn();
});
$("#twelve").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
  $("#twelve").hide();
  $("#stage3").show();
  $("#stage3").fadeOut(2500);
  $("#bomb").show();
  $("#bomb").fadeOut(2000);
  $("#thirteen").show();
  $("#thirteen").fadeOut(12000);
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover").delay(5000).fadeIn();
});

$("#thirteen").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#thirteen").hide();
$("#bomb2").show();
$("#bomb2").fadeOut(1000);
$("#fourteen").show();
$("#fourteen").fadeOut(1500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });


  $("#fourteen").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#fourteen").hide();
$("#bomb3").show();
$("#bomb3").fadeOut(1000);
$("#fifteen").show();
$("#fifteen").fadeOut(1500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });


$("#fifteen").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#fifteen").hide();
$("#bomb4").show();
$("#bomb4").fadeOut(1000);
$("#sixteen").show();
$("#sixteen").fadeOut(1500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#sixteen").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#sixteen").hide();
$("#bomb5").show();
$("#bomb5").fadeOut(1000);
$("#seventeen").show();
$("#seventeen").fadeOut(1500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#seventeen").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#seventeen").hide();
$("#bomb6").show();
$("#bomb6").fadeOut(500);
$("#eighteen").show();
$("#eighteen").fadeOut(500);
$("#stagefour").show();
$("#stagefour").fadeOut(2500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#eighteen").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#eighteen").hide();
$("#bomb7").show();
$("#bomb7").fadeOut(500);
$("#nineteen").show();
$("#nineteen").fadeOut(1000);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#nineteen").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#nineteen").hide();
$("#bomb8").show();
$("#bomb8").fadeOut(500);
$("#twenty").show();
$("#twenty").fadeOut(1000);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#twenty").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#twenty").hide();
$("#bomb9").show();
$("#bomb9").fadeOut(500);
$("#twentyone").show();
$("#twentyone").fadeOut(1000);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#twentyone").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#twentyone").hide();
$("#bomb10").show();
$("#bomb10").fadeOut(500);
$("#twentytwo").show();
$("#twentytwo").fadeOut(1000);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#twentytwo").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#twentytwo").hide();
$("#bomb11").show();
$("#bomb11").fadeOut(500);
$("#twentythree").show();
$("#twentythree").fadeOut(1000);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#twentythree").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#twentythree").hide();
$("#bomb12").show();
$("#bomb12").fadeOut(300);
$("#bomb13").show();
$("#bomb13").fadeOut(300);
$("#laststage").show();
$("#laststage").fadeOut(1500);
$("#twentyfour").show();
$("#twentyfour").fadeOut(500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#twentyfour").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#twentyfour").hide();
$("#bomb14").show();
$("#bomb14").fadeOut(300);
$("#bomb15").show();
$("#bomb15").fadeOut(300);
$("#twentyfive").show();
$("#twentyfive").fadeOut(500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#twentyfive").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#twentyfive").hide();
$("#bomb16").show();
$("#bomb16").fadeOut(300);
$("#bomb17").show();
$("#bomb17").fadeOut(300);
$("#twentysix").show();
$("#twentysix").fadeOut(500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#twentysix").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#twentysix").hide();
$("#bomb18").show();
$("#bomb18").fadeOut(300);
$("#bomb19").show();
$("#bomb19").fadeOut(300);
$("#twentyseven").show();
$("#twentyseven").fadeOut(500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#twentyseven").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#twentyseven").hide();
$("#bomb24").show();
$("#bomb24").fadeOut(300);
$("#twentyeight").show();
$("#twentyeight").fadeOut(400);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#twentyeight").click(function(){
   $("#pagerefresh").hide();
    $("#gameover").hide();
$("#twentyeight").hide();
$("#end").show();
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover").delay(5000).fadeIn();
 });

$("#bomb").click(function(){
  $("#gameover").show();
});
$("#bomb1").click(function(){
  $("#gameover").show();
});
$("#bomb2").click(function(){
  $("#gameover").show();
});
$("#bomb3").click(function(){
  $("#gameover").show();
});
$("#bomb4").click(function(){
  $("#gameover").show();
});
$("#bomb5").click(function(){
  $("#gameover").show();
});
$("#bomb6").click(function(){
  $("#gameover").show();
});
$("#bomb7").click(function(){
  $("#gameover").show();
});
$("#bomb8").click(function(){
  $("#gameover").show();
});
$("#bomb9").click(function(){
  $("#gameover").show();
});
$("#bomb10").click(function(){
  $("#gameover").show();
});
$("#bomb11").click(function(){
  $("#gameover").show();
});
$("#bomb12").click(function(){
  $("#gameover").show();
});
$("#bomb13").click(function(){
  $("#gameover").show();
});
$("#bomb14").click(function(){
  $("#gameover").show();
});
$("#bomb15").click(function(){
  $("#gameover").show();
});
$("#bomb16").click(function(){
  $("#gameover").show();
});
$("#bomb17").click(function(){
  $("#gameover").show();
});
$("#bomb18").click(function(){
  $("#gameover").show();
});
$("#bomb19").click(function(){
  $("#gameover").show();
});
$("#bomb20").click(function(){
  $("#gameover").show();
});
$("#bomb21").click(function(){
  $("#gameover").show();
});
$("#bomb22").click(function(){
  $("#gameover").show();
});
$("#bomb23").click(function(){
  $("#gameover").show();
});
$("#bomb24").click(function(){
  $("#gameover").show();
});

$("#back").click(function(){
$("#back").hide();
$("#iword").hide();
$("#iword2").hide();
$("#word3").hide();
$("#word4").hide();
$("#word5").hide();
$("#word6").hide();
$("#word7").hide();
$("#word8").hide();
$("#word9").hide();
$("#word10").hide();
$("#word11").hide();
$("#box").hide();
$("#title").delay(1000).fadeIn();
$("#title2").delay(2000).fadeIn();
$("#start").delay(3000).fadeIn();
$("#instruction").delay(4000).fadeIn();
});

})
